# Generated by Django 3.1.6 on 2021-02-15 22:59

from django.db import migrations

import dandiapi.api.models.asset
import dandiapi.api.models.validation
import dandiapi.api.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_metadata_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetblob',
            name='blob',
            field=dandiapi.api.storage.DeconstructableFileField(
                blank=True,
                max_length=256,
                storage=dandiapi.api.models.asset._get_asset_blob_storage,
                upload_to=dandiapi.api.models.asset._get_asset_blob_prefix,
            ),
        ),
        migrations.AlterField(
            model_name='validation',
            name='blob',
            field=dandiapi.api.storage.DeconstructableFileField(
                blank=True,
                max_length=256,
                storage=dandiapi.api.models.validation._get_validation_blob_storage,
                upload_to=dandiapi.api.models.validation._get_validation_blob_prefix,
            ),
        ),
    ]
